Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Account
{
    public class LoginModel : PageModel
    {
        private SignInManager<User> _signInManager;
        private UserManager<User> _userManager;
        public LoginModel(SignInManager<User> signInManager, UserManager<User> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public void OnGet(string value)
        {
            if (!string.IsNullOrWhiteSpace(value))
            {
                if (value.Equals("accessdenied"))
                {
                    ViewData["message"] = "You do not have access to that page, please sign in with the right acocunt.";
                }
            }
        }


        public async Task<IActionResult> OnPostSignIn(string user, string password, bool rememberMe = false)
        {

            User usr = user.Contains("@") ? await _userManager.FindByEmailAsync(user) : await _userManager.FindByNameAsync(user);

            if (usr is not null)
            {

                rememberMe = true;

                var result = await _signInManager.PasswordSignInAsync(usr.Email, password, rememberMe, false);

                if (result.Succeeded)
                {
                   return LocalRedirect("/");
                }
                else
                {
                    ViewData["message"] = "Check your password";
         
                }

            }
            else
            {
                ViewData["message"] = "User does not exist";
         
            }

            return Page();

        }
    }
}

Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace BookTalk.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private SignInManager<User> _signInManager;
        public LogoutModel(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
        }

        public async Task<IActionResult> OnGet()
        {

            // Sign out user
            if (HttpContext.Request.Cookies.Count > 0)
            {
                var siteCookies = HttpContext.Request.Cookies.Where(c => c.Key.Contains(".AspNetCore.") || c.Key.Contains("Microsoft.Authentication") || c.Key.Contains("BookTalkCookie"));

                foreach (var cookie in siteCookies)
                {
                    Response.Cookies.Delete(cookie.Key);
                }
            }

            await _signInManager.SignOutAsync();

            return LocalRedirect("/");


        }




    }
}

Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BookTalk.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Account
{
    public class RegisterModel : PageModel
    {

        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly Context _context;


        public RegisterModel(UserManager<User> userManager, Context context, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _context = context;
            _signInManager = signInManager;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostRegisterAccount(string email, string password, string confirmPassword)
        {


            if (password.Equals(confirmPassword))
            {
                User user = await _userManager.FindByEmailAsync(email);

                if (user is not null)
                {
                    ViewData["message"] = "There is already a user with this email, try restoring your account instead";
                    return Page();
                }
                else
                {
                    User newUser = new User()
                    {
                        UserName = email,
                        Email = email
                    };

                    var result = await _userManager.CreateAsync(newUser, password);

                    if (result.Succeeded)
                    {

                        if(_context.Users.Count() == 1)
                        {

                            await _userManager.AddToRoleAsync(newUser, "Admin");
                        }
                        else
                        {
                            await _userManager.AddToRoleAsync(newUser, "Customer");
                        }


                        // Sign in user. 

                        var signinResult = await _signInManager.PasswordSignInAsync(newUser, password, false, false);

                        if(signinResult.Succeeded)
                        {

                            return LocalRedirect("/");
                        }
                        else
                        {


                            ViewData["message"] = "Account was created, but failed to sign in.";


                        }

                    }
                    else
                    {

                        ViewData["message"] = "Something happened, please try again";

                    }

                }
                
            }
            else
            {
                ViewData["message"] = "Your password does not match!";
            }

            return Page();

        }
    }
}

Pages/Account/Login.cshtml
@page "{value?}"
@model BookTalk.Pages.Account.LoginModel
@{
}

@section Header{ 

<style>

    body {
        background-color: #282828 !important;
    }
    footer {
        display: none !important;
    }

</style>


}

<div class="row justify-content-md-center">

            <div class="formContainer">


                <center>
                    <div class="formHeader">
                        <i class="fas fa-user large-icon"></i>
                    </div>
                </center>


                <div class="formBody">


                    <form asp-page-handler="SignIn" method="post">


              
                            <div class="col-auto">
                                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fas fa-user"></i></div>
                                    </div>
                                    <input type="text" name="user" class="form-control" id="inlineFormInputGroup" placeholder="Username">
                                </div>
                            </div>

                            <div class="col-auto">
                                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fas fa-key"></i></div>
                                    </div>
                                    <input type="password"  name="password" class="form-control" id="inlineFormInputGroup" placeholder="Password">
                                </div>
                            </div>


                            <div class="form-group form-check">
                                <input name="rememberMe" type="checkbox" class="form-check-input">
                                <label class="form-check-label checbox-large-label" for="exampleCheck1">Keep me signed in!</label>
                            </div>

                            <button type="submit" <i class="fas fa-sign-in-alt"> Login</button>

                            <p style="color: red;">@ViewData["message"]</p>

                    </form>


                </div>

            </div>


        </div>

Pages/Account/Logout.cshtml
@page
@model BookTalk.Pages.Account.LogoutModel

Pages/Account/Register.cshtml
@page
@model BookTalk.Pages.Account.RegisterModel
@{
}


@*<form asp-page-handler="RegisterAccount" method="post">

    <input type="text" placeholder="Email" name="email" />
    <br />
    <input type="password" placeholder="Enter a password" name="password" />
    <br />
    <input type="password" placeholder="Confirm your password" name="confirmPassword" />
    <br />
    <button type="submit">Register</button>
    <br />
    <span style="color: red;">@ViewData["message"]</span>

</form>*@


<div class="row">
    <div class="col-sm-12 col-md-6 col-lg-6 col-center">
        <div class="formContainer">
            <center>
                <div class="formHeader">
                    <i class="fas fa-user large-icon"></i>
                </div>
            </center>
            <div class="formBody">
                <form asp-page-handler="RegisterAccount" method="post">

                    <div class="form-group">
                        <input type="text" class="form-control" name="email" placeholder="email">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="password">
                    </div>

                    <div class="form-group">
                        <input type="password" name="confirmPassword" class="form-control" placeholder="confrim password" />
                    </div>

                    <div class="form-group form-check">
                        <input type="checkbox" name="rememberMe" placeholder="RememberME" value="RememberMe">
                        <label class="form-check-label checbox-large-label" for="exampleCheck1">Keep me signed in!</label>
                    </div>
                    <button type="submit" class="btn btn-orange">Register</button>

                    <p style="color: red;">@ViewData["message"]</p>

                </form>
            </div>
        </div>
    </div>
</div>