Pages/Admin/Content/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Admin.Content
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {

        private Context _context;
        public AddModel(Context context)
        {
            _context = context;
        }

        public void OnGet()
        {
        }


        public void OnPostAddContent(string title, string body, string imgurl, bool isinmenu, bool ispublished, int menuorder)
        {
            try
            {
                Data.Content content = new Data.Content(title, body = body, isinmenu, ispublished, imgurl, menuorder);

                _context.Content.Add(content);

                _context.SaveChanges();

                ViewData["message"] = "Your content has been added!";

            }
            catch (Exception ex)
            {
                ViewData["message"] = $"Something went wrong. Error: {ex}";
            }

        }

    }
}

Pages/Admin/Content/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BookTalk.Pages.Admin.Content
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {

        private Context _context;

        [BindProperty]
        public Data.Content _content { get; set; }
        public EditModel(Context context)
        {
            _context = context;
        }

        public void OnGet(string contentid)
        {
            _content = _context.Content.Where(x => x.Id == contentid).FirstOrDefault();

            _context.Entry(_content).State = EntityState.Detached;


            if (_content is null)
            {
                ViewData["message"] = "Content was not found!";
            }
        }


        public void OnPostSaveContent(string title, string body, string imgurl, bool isinmenu, bool ispublished, int menuorder, string contentid)
        {
            try
            {

                Data.Content dc = _context.Content.Where(x => x.Id == contentid).FirstOrDefault();

                _context.Entry(dc).State = EntityState.Modified;

                // force
                ispublished = true;
                isinmenu = true;

                dc.Title = title;
                dc.Body = body;
                dc.ImageUrl = imgurl;
                dc.IsInMenu = isinmenu;
                dc.IsPublished = ispublished;
                dc.MenuOrder = menuorder;
                
                _context.Content.Update(dc);

                _context.SaveChanges();

                ViewData["message"] = "Your content has been updated!";

            }
            catch (Exception ex)
            {
                ViewData["message"] = $"Something went wrong. Error: {ex}";
            }

        }

    }
}

Pages/Admin/Content/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BookTalk.Data;
using Microsoft.AspNetCore.Authorization;

namespace BookTalk.Pages.Admin.Content
{

    [Authorize( Roles = "Admin")]
    public class IndexModel : PageModel
    {
        private readonly Context _context;


        [BindProperty]
        public List<ContentListModel> contentList { get; set; }

        private static List<ContentListModel> _cl = new List<ContentListModel>();


        public IndexModel(Context context)
        {
            _context = context;

            contentList = new List<ContentListModel>();

            

        }


        public void OnGet()
        {

            if (contentList is null)
            {
                contentList = _cl;
            }

            RefreshContent();

            

        }


        private void RefreshContent()
        {

            foreach (var content in _context.Content.ToList())
            {

                ContentListModel model = new ContentListModel
                {
                    Id = content.Id,
                    Title = content.Title,
                    Body = content.Body,
                    ImageUrl = content.ImageUrl,
                    IsInMenu = content.IsInMenu,
                    IsPublished = content.IsPublished,
                    MenuOrder = content.MenuOrder

                };

                contentList.Add(model);

                contentList = contentList.OrderBy(x => x.MenuOrder).ToList();

                _cl = contentList;

            }
        }

        public IActionResult OnPostDeleteContent(string contentid)
        {
            Data.Content content = _context.Content.Where(x => x.Id == contentid).FirstOrDefault();

            if (content is not null)
            {

                _context.Content.Remove(content);
                _context.SaveChanges();
            
            }

            RefreshContent();

            return Page();
   
        }



    }
}

Pages/Admin/Store/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Admin.Store
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {

        private Context _context;

        public AddModel(Context context)
        {
            _context = context;
        }

        public void OnGet()
        {
        }


        public IActionResult OnPostAddNewBook(string title, string description, string coverurl, double price, int stock, int sale )
        {

            try 
            {
                Book book = new Book(title, description, coverurl, price, stock, sale, false, true);

                _context.Books.Add(book);

                _context.SaveChanges();

                ViewData["message"] = "Book has been saved!";

                return LocalRedirect($"/admin/store/{book.Id}");
            }
            catch(Exception ex)
            {
                ViewData["message"] = $"Something went wrong! {ex}";

                return Page();

            }


        }


    }
}

Pages/Content.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using BookTalk.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages
{
    public class ContentModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private Context _context;
        private EmailService _email;

        public ContentPageModel contentModel;

        [BindProperty]
        public SendEmailModel emailModel { get; set; }

        public bool showContactForm = false;
        public bool showEmailSentSuccess = false;
        public ContentModel(Context context, EmailService emailService)
        {
            _context = context;
            _email = emailService;
            contentModel = new ContentPageModel();
        }

        public void OnGet(string pageName)
        {

            if (pageName.ToLower().Equals("Contact".ToLower()))
            {
                showContactForm = true;
            }
            else
            {
                showContactForm = false;
            }

            if (pageName is not null)
            {
                // Get the current content named in "page string" from database using the title as a find atribute.
                Data.Content content = _context.Content.Where(page => page.Title.Equals(pageName)).FirstOrDefault();
                
                if (content is not null) 
                {
                    if (content.IsPublished)
                    {
                        contentModel.Title = content.Title;
                        contentModel.Body = content.Body;
                        contentModel.ImageUrl = content.ImageUrl;
                    }
                    else
                    {
                        contentModel.Title = "Sorry, this page has not been published";
                    }
                }
                else
                {
                    contentModel.Title = "Sorry, this page does not exist (404)";
                }

            }
            else
            {
                contentModel.Title = "Sorry, you have no query";
            }

        }


        public void OnPostSendEmail(IFormFile file)
        {
            bool didSend =_email.SendContactEmail(emailModel);

            if (didSend)
            {
                showEmailSentSuccess = true;
            }
        }
    }
}

Pages/Admin/Content/Add.cshtml
@page
@model BookTalk.Pages.Admin.Content.AddModel
@{
}


        @*public string Title { get; set; }
        public string Body { get; set; }
        public string ImageUrl { get; set; }
        public bool IsInMenu { get; set; }
        public bool IsPublished { get; set; }

        public int MenuOrder { get; set; }*@


<form asp-page-handler="AddContent" method="post">

    <input type="text" placeholder="Enter the title" name="title" />
    <br />
    <textarea name="body" placeholder="Content body..."></textarea>
    <br />
    <input type="text" placeholder="Image URL" name="imgurl" />
    <br />
    <input type="checkbox" name="isinmenu" />
    <label for="isinmenu">In menu</label>
    <br />
    <input type="checkbox" name="ispublished" />
    <label for="ispublished">Publish</label>
    <br />
    <input type="number" placeholder="Order in menu" name="menuorder" />
    <br />
    <button>Add!</button>
    <br />
    <span style="color:red;">@ViewData["message"]</span>

</form>

Pages/Admin/Content/Edit.cshtml
@page "{contentid}"
@model BookTalk.Pages.Admin.Content.EditModel

<form asp-page-handler="SaveContent" method="post">

    <input type="text" placeholder="Enter the title" name="title" value="@Model._content.Title" />
    <br />
    <textarea name="body" placeholder="Content body...">@Model._content.Body</textarea>
    <br />
    <input type="text" placeholder="Image URL" name="imgurl" value="@Model._content.ImageUrl"/>
    <br />
    <input type="checkbox" name="isinmenu" value="@Model._content.IsInMenu"/>
    <label for="isinmenu">In menu</label>
    <br />
    <input type="checkbox" name="ispublished" value="@Model._content.IsPublished" />
    <label for="ispublished">Publish</label>
    <br />
    <input type="number" placeholder="Order in menu" name="menuorder" value="@Model._content.MenuOrder" />
    <br />
    <input type="hidden" name="contentid" value="@Model._content.Id" />
    <button>Update!</button>
    <br />
    <span style="color:red;">@ViewData["message"]</span>

</form>

Pages/Admin/Content/Index.cshtml
@page
@model BookTalk.Pages.Admin.Content.IndexModel

<ul class="nav justify-content-center adminNav">

    <li class="nav-item">
        <a class="nav-link noHover" href="#">Tools: </a>
    </li>

    <li class="nav-item">
        <a class="nav-link active" href="/admin/content/add"><i class="fas fa-plus-square"></i></a>
    </li>

</ul>

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">Order</th>
            <th scope="col">Image</th>
            <th scope="col">Title</th>
            <th scope="col">Menu</th>
            <th scope="col">Published</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>

        @for (int i = 0; i < Model.contentList.Count; i++)
        {


            <tr>
                <th scope="row">@Model.contentList[i].MenuOrder</th>
                <td><img src="@Model.contentList[i].ImageUrl" alt="" class="img-fluid" style="max-height: 20px;" /></td>
                <td>@Model.contentList[i].Title</td>
                <td>@Model.contentList[i].IsInMenu</td>
                <td>@Model.contentList[i].IsPublished</td>
                <td><a href="/admin/content/edit/@Model.contentList[i].Id"><i class="fas fa-edit"></i></a></td>

                <td>

                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_@i">
                        <i class="fas fa-trash-alt"></i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="modal_@i" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Delete Warning!</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Delete @Model.contentList[i].Title ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                                    <form asp-page-handler="DeleteContent" method="post">

                                        <input type="hidden" value="@Model.contentList[i].Id" name="contentid" />


                                        <button class="btn btn-primary">Yes</button>

                                    </form>




                                </div>
                            </div>
                        </div>
                    </div>




                </td>

            </tr>

        }

    </tbody>
</table>