Pages/Checkout/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using BookTalk.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Checkout
{
    public class IndexModel : PageModel
    {

        private readonly Context _context;
        private CustomerCartService _cartService;

        [BindProperty]
        public List<Book> BooksInCart { get; set; } = new List<Book>();


        public IndexModel(Context context, CustomerCartService cartService)
        {
            _context = context;
            _cartService = cartService;

            _cartService.GetCheckoutSum().ForEach(delegate(CheckoutSummary model) 
            {
                Book book = _context.Books.Where(x => x.Id == model.Book.Id).FirstOrDefault();

                if (book is not null)
                {
                    BooksInCart.Add(book);
                }

            });

        }

        public void OnGet()
        {
        }


        public void OnPostRemoveFromCart(string bookid)
        {
            _cartService.RemoveFromCart(bookid);


        }


        public void OnPostDecrementItem(string bookid)
        {
            _cartService.DecrementItem(bookid);

        }

        public void OnPostAddToCart(string bookid)
        {
            _cartService.AddToCart(bookid);

        }

    }
}

Pages/Checkout/Summary.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Checkout
{
    [Authorize( Roles = "Customer,Admin")]
    public class SummaryModel : PageModel
    {
        private Context _context;
        private CustomerCartService _cartService;


        public SummaryModel(Context context, CustomerCartService cartService)
        {
            _context = context;
            _cartService = cartService;
        }


        public void OnGet()
        {
        }


        public IActionResult OnPostConfirmSummary(string name, string address, string secondaddress, string provenance, string zipcode, string city)
        {

            User user = _context.Users.Where(x => x.UserName.Equals(User.Identity.Name)).FirstOrDefault();

            if (user is not null)
            {
                Order order = new Order();
                List<UserOrder> userOrders = new List<UserOrder>();

                _cartService.GetCheckoutSum().ForEach(item =>
                {

                    UserOrder userOrder = new UserOrder(order, item.Book);

                    userOrders.Add(userOrder);

                });

                order.Status = "Order summarized";
                order.Finnished = false;
                order.PaymentMethod = "Not Selected";
                order.TotalPrice = _cartService.GetCheckoutSum().Sum(x => x.Book.Price * x.Quantity);

                order.Name = name;
                order.Address = address;
                order.SecondAddress = secondaddress;
                order.Provenance = provenance;
                order.ZipCode = zipcode;
                order.City = city;


                order.User = user;
                order.UserId = user.Id;
                order.UserOrder = userOrders;


                _context.Orders.Add(order);
                _context.SaveChanges();


                return LocalRedirect($"checkout/payment/{order.Id}");
            }
            else
            {
                return Page();
            }
            
        
        }
    }
}

Pages/Checkout/Index.cshtml
@page
@model BookTalk.Pages.Checkout.IndexModel
@{ }

@inject CustomerCartService cartService;



<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Media</th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col"> </th>
            <th scope="col"><center>Quantity</center></th>
            <th scope="col"> </th>
            <th scope="col"><center>Remove</center></th>
        </tr>
    </thead>
    <tbody>

        @{ int count = 1;

                        foreach (var sum in cartService.GetCheckoutSum())
                        {
            <tr>
                <th scope="row">@count</th>
                <td><img src="@sum.Book.CoverUrl" alt="@sum.Book.Title" class="img-fluid cartMedia" /></td>

                <td>@sum.Book.Title</td>
                <td>@sum.Book.Price</td>




                <td>
                    <center>
                        <form asp-page-handler="DecrementItem" method="post">

                            <input type="hidden" value="@sum.Book.Id" name="bookid" />

                            <button class="btn-clear"><i class="fas fa-arrow-alt-circle-left"></i></button>


                        </form>
                    </center>
                </td>
                <td>
                    <center>
                        @sum.Quantity
                    </center>
                </td>
                <td>
                    <center>
                        <form asp-page-handler="AddToCart" method="post">

                            <input type="hidden" value="@sum.Book.Id" name="bookid" />

                            <button class="btn-clear"><i class="fas fa-arrow-alt-circle-right"></i></button>
                        </form>
                    </center>
                </td>
                <td>

                    <center>
                        <form asp-page-handler="RemoveFromCart" method="post">
                            <input type="hidden" value="@sum.Book.Id" name="bookid" />
                            <button class="btn-clear">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                    </center>
                </td>
            </tr> count++;
                        } }


    </tbody>
</table>



<table class="float-lg-right">

    <tr>
        <td>
            <table class="float-right">
                <tr>
                    <td class="right-align-text"><b>Total:</b> </td>
                    <td class="table-spacer"></td>
                    <td>@cartService.GetCheckoutSum().Sum(x => x.Book.Price * x.Quantity)</td>
                </tr>

                <tr>
                    <td><b>VAT:</b> </td>
                    <td class="table-spacer"></td>
                    <td>0%</td>
                </tr>
            </table>
        </td>
    </tr>

    <tr>
        <td>
            <a href="/checkout/summary" class="btn btn-lg checkout-sum-button float-right" role="button" aria-pressed="true">Proceed to Payment details</a>
        </td>
    </tr>


</table>

Pages/Checkout/Summary.cshtml
@page
@model BookTalk.Pages.Checkout.SummaryModel
@{
}

@inject CustomerCartService cartService;

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
        </tr>
    </thead>
    <tbody>

        @{

            int count = 1;

            foreach (var sum in cartService.GetCheckoutSum())
            {
                <tr>
                    <th scope="row">@count</th>
                    <td>@sum.Book.Title</td>
                    <td>@sum.Book.Price</td>
                    <td>@sum.Quantity</td>
                
                </tr>

                count++;
            }

        }


    </tbody>
</table>

<div class="CheckoutConsole">

    <table>

        <tr>

            <td>Total: </td>
            <td>@cartService.GetCheckoutSum().Sum(x => x.Book.Price * x.Quantity)</td>
        </tr>


        <tr>

            <td>VAT: </td>
            <td>0%</td>
        </tr>

    </table>


    <div class="col-12" style="text-align: left; direction: ltr;">


        <form asp-page-handler="ConfirmSummary" method="post">
            <div class="form-group row">
                <label for="name" class="col-4 col-form-label">Name</label>
                <div class="col-8">
                    <input id="name" name="name" placeholder="Enter your name..." type="text" aria-describedby="nameHelpBlock" class="form-control" required="required">
                    <span id="nameHelpBlock" class="form-text text-muted">Please write your first and last name here.</span>
                </div>
            </div>
            <div class="form-group row">
                <label for="address" class="col-4 col-form-label">Address</label>
                <div class="col-8">
                    <input id="address" name="address" placeholder="Address" type="text" aria-describedby="addressHelpBlock" required="required" class="form-control">
                    <span id="addressHelpBlock" class="form-text text-muted">Enter your address here</span>
                </div>
            </div>
            <div class="form-group row">
                <label for="secondaddress" class="col-4 col-form-label">Address 2</label>
                <div class="col-8">
                    <input id="secondaddress" name="secondaddress" placeholder="Second line of address" type="text" aria-describedby="secondaddressHelpBlock" class="form-control">
                    <span id="secondaddressHelpBlock" class="form-text text-muted">(Optional)</span>
                </div>
            </div>
            <div class="form-group row">
                <label for="provenance" class="col-4 col-form-label">Provenance</label>
                <div class="col-8">
                    <input id="provenance" name="provenance" placeholder="Enter your provenance" type="text" class="form-control" required="required">
                </div>
            </div>
            <div class="form-group row">
                <label for="city" class="col-4 col-form-label">City</label>
                <div class="col-8">
                    <input id="city" name="city" placeholder="Enter the name of your city here..." type="text" class="form-control" aria-describedby="cityHelpBlock" required="required">
                    <span id="cityHelpBlock" class="form-text text-muted">Please use the official name</span>
                </div>
            </div>
            <div class="form-group row">
                <label for="zipcode" class="col-4 col-form-label">Zip Code</label>
                <div class="col-8">
                    <input id="zipcode" name="zipcode" placeholder="Enter your zip code here..." type="text" class="form-control" aria-describedby="zipcodeHelpBlock" required="required">
                    <span id="zipcodeHelpBlock" class="form-text text-muted">Any format is accepted.</span>
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-4 col-8">
                    <button name="submit" type="submit" class="btn btn-primary">Proceed to Payment</button>
                </div>
            </div>
        </form>


    </div>


    <br />
    <br />
    <br />
    <br />

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

</div>