Pages/Admin/Content/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Admin.Content
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {

        private Context _context;
        public AddModel(Context context)
        {
            _context = context;
        }

        public void OnGet()
        {
        }


        public void OnPostAddContent(string title, string body, string imgurl, bool isinmenu, bool ispublished, int menuorder)
        {
            try
            {
                Data.Content content = new Data.Content(title, body = body, isinmenu, ispublished, imgurl, menuorder);

                _context.Content.Add(content);

                _context.SaveChanges();

                ViewData["message"] = "Your content has been added!";

            }
            catch (Exception ex)
            {
                ViewData["message"] = $"Something went wrong. Error: {ex}";
            }

        }

    }
}

Pages/Admin/Content/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BookTalk.Pages.Admin.Content
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {

        private Context _context;

        [BindProperty]
        public Data.Content _content { get; set; }
        public EditModel(Context context)
        {
            _context = context;
        }

        public void OnGet(string contentid)
        {
            _content = _context.Content.Where(x => x.Id == contentid).FirstOrDefault();

            _context.Entry(_content).State = EntityState.Detached;


            if (_content is null)
            {
                ViewData["message"] = "Content was not found!";
            }
        }


        public void OnPostSaveContent(string title, string body, string imgurl, bool isinmenu, bool ispublished, int menuorder, string contentid)
        {
            try
            {

                Data.Content dc = _context.Content.Where(x => x.Id == contentid).FirstOrDefault();

                _context.Entry(dc).State = EntityState.Modified;

                // force
                ispublished = true;
                isinmenu = true;

                dc.Title = title;
                dc.Body = body;
                dc.ImageUrl = imgurl;
                dc.IsInMenu = isinmenu;
                dc.IsPublished = ispublished;
                dc.MenuOrder = menuorder;
                
                _context.Content.Update(dc);

                _context.SaveChanges();

                ViewData["message"] = "Your content has been updated!";

            }
            catch (Exception ex)
            {
                ViewData["message"] = $"Something went wrong. Error: {ex}";
            }

        }

    }
}

Pages/Admin/Content/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BookTalk.Data;
using Microsoft.AspNetCore.Authorization;

namespace BookTalk.Pages.Admin.Content
{

    [Authorize( Roles = "Admin")]
    public class IndexModel : PageModel
    {
        private readonly Context _context;


        [BindProperty]
        public List<ContentListModel> contentList { get; set; }

        private static List<ContentListModel> _cl = new List<ContentListModel>();


        public IndexModel(Context context)
        {
            _context = context;

            contentList = new List<ContentListModel>();

            

        }


        public void OnGet()
        {

            if (contentList is null)
            {
                contentList = _cl;
            }

            RefreshContent();

            

        }


        private void RefreshContent()
        {

            foreach (var content in _context.Content.ToList())
            {

                ContentListModel model = new ContentListModel
                {
                    Id = content.Id,
                    Title = content.Title,
                    Body = content.Body,
                    ImageUrl = content.ImageUrl,
                    IsInMenu = content.IsInMenu,
                    IsPublished = content.IsPublished,
                    MenuOrder = content.MenuOrder

                };

                contentList.Add(model);

                contentList = contentList.OrderBy(x => x.MenuOrder).ToList();

                _cl = contentList;

            }
        }

        public IActionResult OnPostDeleteContent(string contentid)
        {
            Data.Content content = _context.Content.Where(x => x.Id == contentid).FirstOrDefault();

            if (content is not null)
            {

                _context.Content.Remove(content);
                _context.SaveChanges();
            
            }

            RefreshContent();

            return Page();
   
        }



    }
}

Pages/Admin/Store/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Admin.Store
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {

        private Context _context;

        public AddModel(Context context)
        {
            _context = context;
        }

        public void OnGet()
        {
        }


        public IActionResult OnPostAddNewBook(string title, string description, string coverurl, double price, int stock, int sale )
        {

            try 
            {
                Book book = new Book(title, description, coverurl, price, stock, sale, false, true);

                _context.Books.Add(book);

                _context.SaveChanges();

                ViewData["message"] = "Book has been saved!";

                return LocalRedirect($"/admin/store/{book.Id}");
            }
            catch(Exception ex)
            {
                ViewData["message"] = $"Something went wrong! {ex}";

                return Page();

            }


        }


    }
}

Pages/Admin/Store/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages.Admin.Store
{
    [Authorize( Roles = "Admin")]
    public class IndexModel : PageModel
    {
        private readonly Context _context;

        public List<Book> books { get; set; } = new List<Book>();

        public IndexModel(Context context)
        {
            _context = context;
            books = _context.Books.ToList();
        }
        public void OnGet(string value)
        {
            if (!string.IsNullOrWhiteSpace(value))
            {

                ViewData["message"] = $"Book added: {_context.Books.Where(x => x.Id == value).FirstOrDefault().Title}";

            }
            else
            {

                ViewData["message"] = string.Empty;
            }
        }
    }
}

Pages/Book.cshtml.cs
using System;
using System.Collections.Generic;
using BookTalk.Data;
using BookTalk.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages
{
    public class BookModel : PageModel
    {
        private Context _context;

        public BookPageModel contentModel;
        public BookModel(Context context)
        {
            _context = context;
            contentModel = new BookPageModel();
        }

        public void OnGet(string bookId)
        {
            Book book = _context.Books.Find(bookId);

            contentModel.Title = book.Title;
            contentModel.Description = book.Description;
            contentModel.ImageUrl = book.CoverUrl;
            contentModel.Price = book.Price;
        }
    }


}

Pages/Content.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using BookTalk.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages
{
    public class ContentModel : Microsoft.AspNetCore.Mvc.RazorPages.PageModel
    {
        private Context _context;
        private EmailService _email;

        public ContentPageModel contentModel;

        [BindProperty]
        public SendEmailModel emailModel { get; set; }

        public bool showContactForm = false;
        public bool showEmailSentSuccess = false;
        public ContentModel(Context context, EmailService emailService)
        {
            _context = context;
            _email = emailService;
            contentModel = new ContentPageModel();
        }

        public void OnGet(string pageName)
        {

            if (pageName.ToLower().Equals("Contact".ToLower()))
            {
                showContactForm = true;
            }
            else
            {
                showContactForm = false;
            }

            if (pageName is not null)
            {
                // Get the current content named in "page string" from database using the title as a find atribute.
                Data.Content content = _context.Content.Where(page => page.Title.Equals(pageName)).FirstOrDefault();
                
                if (content is not null) 
                {
                    if (content.IsPublished)
                    {
                        contentModel.Title = content.Title;
                        contentModel.Body = content.Body;
                        contentModel.ImageUrl = content.ImageUrl;
                    }
                    else
                    {
                        contentModel.Title = "Sorry, this page has not been published";
                    }
                }
                else
                {
                    contentModel.Title = "Sorry, this page does not exist (404)";
                }

            }
            else
            {
                contentModel.Title = "Sorry, you have no query";
            }

        }


        public void OnPostSendEmail(IFormFile file)
        {
            bool didSend =_email.SendContactEmail(emailModel);

            if (didSend)
            {
                showEmailSentSuccess = true;
            }
        }
    }
}

Pages/Demo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestSharp;
using Newtonsoft.Json;
using System.Net;

namespace BookTalk.Pages
{
    public class DemoModel : PageModel
    {

        [BindProperty]
        public List<UserModel> Users { get; set; } = new List<UserModel>();

        public void OnGet()
        {
            Users = GetUsers();
        }



        public IActionResult OnPostLogin(string user, string password)
        {
            // prepare your body
            var body = new
            {
                user = user,
                password = password
            };

            //convert body to json
            string json = JsonConvert.SerializeObject(body, Formatting.Indented);


            RestClient client = new RestClient("https://localhost:44362/UserPlayground/login");

            RestRequest request = new RestRequest 
            { 
                Method = Method.POST
            };

            request.Parameters.Clear();
            request.AddHeader("Content-Type", "application/json");
            request.AddParameter("application/json", json, ParameterType.RequestBody);

            IRestResponse response = client.Execute(request);


            if (response.StatusCode == HttpStatusCode.OK)
            {

                UserLoginSuccessModel message = JsonConvert.DeserializeObject<UserLoginSuccessModel>(response.Content);

                ViewData["message"] = $"{message.message} - Token: {message.token}";

            }
            else
            {
                UserLoginError message = JsonConvert.DeserializeObject<UserLoginError>(response.Content);

                ViewData["message"] = message.message;
            }


            return Page();
        }


        public List<UserModel> GetUsers()
        {

            // Set the url
            RestClient client = new RestClient("https://localhost:44362/UserPlayground/getusers");

            // Set the http method post,get,put,delete.etc
            RestRequest request = new RestRequest 
            { 
                Method = Method.GET
            };

            // optional clear parameters
            request.Parameters.Clear();

            // Execute the request
            IRestResponse response = client.Execute(request);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                // Convert the request to an object from a json.
                List<UserModel> users = JsonConvert.DeserializeObject<List<UserModel>>(response.Content);
                // return the result
                return users;
            }
            else
            {
                return null;
            }

        }


        

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BookTalk.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using BookTalk.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookTalk.Pages
{
    public class IndexModel : PageModel
    {
        private readonly Context _context;
        private CustomerCartService _cartService;

        [BindProperty]
        public List<Book> bookList { get; set; }

        public IndexModel(Context context, CustomerCartService cartService)
        {
            _context = context;
            _cartService = cartService;
            bookList = _context.Books.Where(x => x.IsFeatured.Equals(true) || x.Sale > 0).ToList();
        }

        public void OnGet()
        {

            _context.Books.ToList().ForEach(x => {

                _cartService.AddToCart(x.Id);

            });

        }


    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookTalk.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using BookTalk.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages
{
    public class ProductsModel : PageModel
    {
        public string Name { get; private set; }

        public List<Book> Books { get; private set; }

        private Context _context;

        public ProductsModel(Context context)
        {
            _context = context;

            Books = _context.Books.ToList();
        }

        public void OnGet()
        {

        }

    }
}

Pages/Store.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookTalk.Data;
using BookTalk.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookTalk.Pages
{
    public class StoreModel : PageModel
    {
        public string Name { get; private set; }

        public List<Book> Books { get; private set; }

        private Context _context;
        private CustomerCartService _cartService;

        public StoreModel(Context context, CustomerCartService cartService)
        {
            _context = context;
            _cartService = cartService;
            Books = _context.Books.ToList();
        }

        public void OnGet()
        {

        }

        public IActionResult OnPostAddToCart(string bookId)
        {
            _cartService.AddToCart(bookId);

            return LocalRedirect("/store");
        }

    }
}

Pages/Book.cshtml
@page "{bookId}"
@model BookTalk.Pages.BookModel


<div>

    <h1>@Model.contentModel.Title</h1>

    @if (!string.IsNullOrEmpty(Model.contentModel.ImageUrl))
    {
        <img src="@Model.contentModel.ImageUrl" class="img-fluid" alt="" />
    }

    <p>@Model.contentModel.Description</p>
    <p>@Model.contentModel.Price SEK</p>

</div>

Pages/Content.cshtml
@page "{pageName}"  
@model BookTalk.Pages.ContentModel


<div>

    <h1>@Model.contentModel.Title</h1>

    @if (!string.IsNullOrEmpty(Model.contentModel.ImageUrl))
    {
        <img src="@Model.contentModel.ImageUrl" class="img-fluid" alt="" />
    }




    @Html.Raw(@Model.contentModel.Body)



    @if (Model.showContactForm)
    {


<form asp-page-handler="SendEmail" method="post">

    <div class="form-group">
        <input type="email" class="form-control" asp-for="emailModel.Email" placeholder="Email" />
    </div>


    <div class="form-group">

        <input type="text" class="form-control" asp-for="emailModel.Message" placeholder="Message..." />

    </div>
    <div class="form-group">

        <input type="file" name="file">

    </div>

    
    <div class="form-group">

        <button type="submit" class="btn btn-primary">Send</button>

    </div>


</form>



    }

    @if (Model.showEmailSentSuccess)
    {

        <span>EMAIL WAS SENT</span>
    }

</div>

Pages/Demo.cshtml
@page
@model BookTalk.Pages.DemoModel
@{
}


<form asp-page-handler="Login" method="post">

    <input type="text" placeholder="Enter your username or password" name="user" />
    <br />
    <br />
    <input type="password" placeholder="Enter your password" name="password" />
    <br />
    <br />
    <button>Login</button>
    <br />
    <br />
    <span style="color: red;">@ViewData["message"]</span>


</form>

<hr />


@foreach (var user in Model.Users)
{
    <div>
        <span>Email: @user.Email</span><br />
        <span>User: @user.Name</span><br />
        <span>Password: @user.Password</span><br />
    </div>
    <hr />
}

Pages/Index.cshtml
@page

@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">



    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
        <i class="fas fa-arrow-alt-circle-left carousel-arrows"></i>
    </a>


    <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
        <i class="fas fa-arrow-alt-circle-right carousel-arrows"></i>
    </a>


    <ol class="carousel-indicators">

        @for (int i = 0; i < Model.bookList.Count; i++)
        {
<li data-target="#carouselExampleCaptions" data-slide-to="@i" class="@(i == 0 ? "active" : string.Empty)"></li>}

    </ol>

    <div class="carousel-inner">

        @for (int i = 0; i < Model.bookList.Count; i++)
        {

<div class="carousel-item @(i == 0 ? "active" : string.Empty)" data-interval="10000">
    <div class="layerOne">
        <div class="floatLeft">

            <img src="@Model.bookList[i].CoverUrl" class="d-block img-ontop img-fluid" alt="...">
        </div>
        <div class="floatRight vertical-center">

            <span class="carousel-title">
                <a href="/store/detail/@Model.bookList[i].Id"> @Model.bookList[i].Title</a>

                @if (@Model.bookList[i].Sale > 0)
                {
<span class="badge badge-warning">@Model.bookList[i].Sale%</span>}

            </span>


            <p class="carousel-p">@Model.bookList[i].Description</p>
        </div>

    </div>

    <div style="background-image: url('@Model.bookList[i].CoverUrl')" class="layerTwo"></div>
</div>}

    </div>


</div>

Pages/Products.cshtml
@page
@model BookTalk.Pages.ProductsModel

@inject CurrencyService currencyService;

<div class="row">




    @foreach (var book in Model.Books)
    {
    <div class="col-lg-3 col-md-6 col-sm-12 ">

        <div class="p-6">
            <div class="card">
                <img src="@book.CoverUrl" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@book.Title</h5>
                    <p class="card-text">@book.Description.Substring(0, 150)...</p>
                    <span>@book.Price SEK</span>
                    <br />

                    <a href="/book/@book.Id" class="btn btn-primary">Show More</a>
                </div>
            </div>
        </div>
    </div>
        

    }
</div>

Pages/Store.cshtml
@page
@model BookTalk.Pages.StoreModel
@inject CurrencyService currencyService;


  
<div class="row">

    @{

        BookTalk.Models.ExchangeRateModel rates = currencyService.Rates();




        @foreach (var book in Model.Books)
        {
            <div class="col-lg-3 col-md-6 col-sm-12 product-space">

                <div class="p-6">
                    <div class="card">
                        <img src="@book.CoverUrl" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@book.Title</h5>
                            <span class="badge badge-primary price-label">@book.Price SEK</span>
                            <br />
                            <span>$@(book.Price * rates.ConversionRates.FirstOrDefault(x => x.Key == "USD").Value)</span>

                            <p class="card-text">@book.Description.Substring(0, 100)...</p>




                            <form asp-page-handler="AddToCart" method="post">
                              
                                <button class="btn btn-primary" type="submit"><i class="fas fa-cart-plus"></i></button>

                                <a href="/book/@book.Id" class="btn btn-primary"><i class="fas fa-info-circle"></i></a>

                                <input type="hidden" name="bookId" value="@book.Id.ToString()" />
                            </form>



                        </div>
                    </div>
                </div>
            </div>


        }

    }
</div>